<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RobloxModelToFilesystem</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RobloxModelToFilesystem</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../extern/RobloxFileFormat/RobloxFileFormat.csproj" />
  </ItemGroup>

</Project>
